from all_tests.hello_world.hello_world import hello_world
from all_tests.hello_world_uart.hello_world_uart import hello_world_uart
from all_tests.vector_all_o.vector_all_o import vector_all_o
from all_tests.vector_all_i.vector_all_i import vector_all_i
from all_tests.vector_all_i_pu.vector_all_i_pu import vector_all_i_pu
from all_tests.vector_all_i_pd.vector_all_i_pd import vector_all_i_pd
from all_tests.vector_all_i_0_1.vector_all_i_0_1 import vector_all_i_0_1
from all_tests.uart.uart import uart
from all_tests.wr_rd_gpio_config.wr_rd_gpio_config import wr_rd_gpio_config
from all_tests.timer0.timer0 import timer0
from all_tests.timer1.timer1 import timer1
from all_tests.timer_chain.timer_chain import timer_chain
from all_tests.spi_master.spi_master import spi_master
from all_tests.housekeeping.hk_reset_val.hk_reset_val import hk_reset_val
from all_tests.housekeeping.hk_wr_regs.hk_wr_regs import hk_wr_regs
from all_tests.housekeeping.cpu_reset.cpu_reset import cpu_reset
from all_tests.irq.hk_spi_irq.hk_spi_irq import hk_spi_irq
from all_tests.irq.external1_irq.external1_irq import external1_irq
from all_tests.irq.external2_irq.external2_irq import external2_irq
from all_tests.irq.spi_master_irq.spi_master_irq import spi_master_irq
from all_tests.irq.timer0_irq.timer0_irq import timer0_irq
from all_tests.irq.timer1_irq.timer1_irq import timer1_irq
from all_tests.temp.temp import temp